services:
  base:
    container_name: react_trt
    image: react:trt
    user: ros
    build:
      target: trt
      context: .
      dockerfile: ./dockerfiles/trt.Dockerfile
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS
    network_mode: host
    ipc: host
    runtime: nvidia
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - USER=${DOCKER_USER}
      - HOME=${DOCKER_HOME}
    volumes:
      - ./bashrc.d:${DOCKER_HOME}/.bashrc.d
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      # Mount ROS workspace and bags
      - ./hydra_ws:${DOCKER_HOME}/hydra_ws
      - ./bags/:${DOCKER_HOME}/bags
      - ./dsg_output:${DOCKER_HOME}/dsg_output
      - ./logs:${DOCKER_HOME}/logs
      - ./models/:${DOCKER_HOME}/models
    privileged: true # GUI related
